### ISSUE TITLE
在建好知识库后，单卡环境启动茴香豆报错

### ISSUE THREAD

**Issue by deep-practice** [InternLM/HuixiangDou#349]
## error log | 日志或报错信息 | ログ
**在建好知识库后，单卡环境启动茴香豆报错：**
启动茴香豆遇到的2个问题：
**1.按如下顺序运行脚本，可以正常工作：**
(1)python3 -m huixiangdou.service.llm_server_hybrid
(2)python3 -m huixiangdou.main
![image](https://github.com/user-attachments/assets/1f164711-f7d2-4286-bc4f-86da7c75d06f)
**2.运行脚本：python3 -m huixiangdou.main --standalone 或者 python3 -m huixiangdou.gradio 会报错：**
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [02:44<00:00, 20.53s/it]
generation_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 123/123 [00:00<00:00, 930kB/s]
Process Process-1:
Traceback (most recent call last):
  File "/root/.conda/envs/demo/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/.conda/envs/demo/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/projects/HuixiangDou/huixiangdou/service/llm_server_hybrid.py", line 716, in llm_serve
    raise (e)
  File "/root/projects/HuixiangDou/huixiangdou/service/llm_server_hybrid.py", line 712, in llm_serve
    server = HybridLLMServer(llm_config=llm_config)
  File "/root/projects/HuixiangDou/huixiangdou/service/llm_server_hybrid.py", line 204, in __init__
    self.inference = InferenceWrapper(model_path)
  File "/root/projects/HuixiangDou/huixiangdou/service/llm_server_hybrid.py", line 115, in __init__
    trust_remote_code=True).cuda().eval()
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2548, in cuda
    return super().cuda(*args, **kwargs)
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 916, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/root/.conda/envs/demo/lib/python3.10/site-packages/torch/cuda/__init__.py", line 300, in _lazy_init
    raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
2024-08-12 13:30:18.119 | ERROR    | huixiangdou.service.llm_server_hybrid:start_llm_server:751 - start local LLM server failed, quit.
Traceback (most recent call last):
  File "/root/.conda/envs/demo/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/.conda/envs/demo/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/projects/HuixiangDou/huixiangdou/main.py", line 194, in <module>
    run()
  File "/root/projects/HuixiangDou/huixiangdou/main.py", line 166, in run
    start_llm_server(config_path=args.config_path)
  File "/root/projects/HuixiangDou/huixiangdou/service/llm_server_hybrid.py", line 752, in start_llm_server
    raise Exception('local LLM path')
Exception: local LLM path

## context | 编译/运行环境 | バックグラウンド
InternStudio 单卡A100 30% cuda12.2
## how to reproduce | 复现步骤 | 再現方法
在构建完知识库后运行
1.python3 -m huixiangdou.main --standalone 或者 python3 -m huixiangdou.gradio

**Comment by tpoisonooo** [comment]
```bash
raise RuntimeError(
RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
```

我修一下。

**Comment by tpoisonooo** [comment]
@deep-practice  首先，这个问题我的环境复现不了。 我的 python 是 3.11

看了下需要创建子 process 需要 spawn 方法，  #351  这两行修改你看是否有效。有的话就 merge

**Comment by deep-practice** [comment]
有效，可以正常运行了!!!
