### ISSUE TITLE
请问如何解决 There is no current event loop in thread %r.'

### ISSUE THREAD

**Issue by 522315428** [InternLM/HuixiangDou#356]
## error log | 日志或报错信息 | ログ
Exception in thread Thread-4 (run):
Traceback (most recent call last):
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/site-packages/nest_asyncio.py", line 26, in run
    loop = asyncio.get_event_loop()
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/site-packages/nest_asyncio.py", line 40, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "/home/pgpu/anaconda3/envs/Huixiangdou/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'

## context | 编译/运行环境 | バックグラウンド
按照requirement 安装，运行本地大模型
## how to reproduce | 复现步骤 | 再現方法

1.python3 -m huixiangdou.gradio  --standalone

**Comment by tpoisonooo** [comment]
@522315428  更新一下代码应该有效。

错误原因，以前是给群聊做的，代码都是 sync。 

1. 为了处理网络搜索反爬虫，做了个启动 chromium 内核模仿人类。 这个 API 需要 async
2. 所以用 event_loop 启动 async

现在要处理更多场景，需要流式。代码用了 async。

async 不能启动这个 loop，崩了。

**Comment by tpoisonooo** [comment]
先临时关掉这个启动内核的行为。要改的地方挺多后面一起改。

**Comment by tpoisonooo** [comment]
我猜你是在说这里：

![image](https://github.com/user-attachments/assets/3e229c93-02ce-46f7-8159-c1ceb1670290)

**Comment by tpoisonooo** [comment]
@522315428   在这个函数前，其他地方调用过  `asyncio.run()` 
`run()` 在结束后会销毁 loop，下次获取会失败。

把所有 `asyncio.run()` 改成不销毁的用法：

```bash
    loop = asyncio.get_event_loop()
    loop.run_until_complete(my_func())
```

**Comment by tpoisonooo** [comment]
@522315428  在这里一起改了，麻烦再试下。
